// <auto-generated />

namespace Tpc.WebIO.Migrations
{
    using System;
    using global::WebIO.DataAccess.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Metadata;
    using Microsoft.EntityFrameworkCore.Migrations;

    [DbContext(typeof(AppDbContext))]
    [Migration("20190904140632_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Creator");

                    b.Property<string>("ModificationComment");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Modifier");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.InterfaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Creator");

                    b.Property<Guid>("DeviceId");

                    b.Property<string>("ModificationComment");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Modifier");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Interfaces");
                });

            modelBuilder.Entity("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.PropertyValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<Guid?>("InterfaceEntityId");

                    b.Property<string>("Key");

                    b.Property<Guid?>("StreamEntityId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("InterfaceEntityId");

                    b.HasIndex("StreamEntityId");

                    b.ToTable("PropertyValueEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PropertyValueEntity");
                });

            modelBuilder.Entity("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.StreamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Creator");

                    b.Property<int>("Direction");

                    b.Property<Guid>("InterfaceId");

                    b.Property<string>("ModificationComment");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Modifier");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.DevicePropertyValueEntity", b =>
                {
                    b.HasBaseType("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.PropertyValueEntity");

                    b.Property<Guid?>("DeviceEntityId");

                    b.HasIndex("DeviceEntityId");

                    b.HasDiscriminator().HasValue("DevicePropertyValueEntity");
                });

            modelBuilder.Entity("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.PropertyValueEntity", b =>
                {
                    b.HasOne("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.InterfaceEntity")
                        .WithMany("Properties")
                        .HasForeignKey("InterfaceEntityId");

                    b.HasOne("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.StreamEntity")
                        .WithMany("Properties")
                        .HasForeignKey("StreamEntityId");
                });

            modelBuilder.Entity("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.DevicePropertyValueEntity", b =>
                {
                    b.HasOne("Tpc.WebIO.DataAccess.EntityFrameworkCore.Entities.DeviceEntity")
                        .WithMany("Properties")
                        .HasForeignKey("DeviceEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
